name: nonsense
on:
  push

# simulate a test that we figure good/bad on based on grepping output (and pass/fail based on exit code of grep). 
# but we also want to _see_ the output in the action, so we know why we're failing. this proves a bit challenging.
# example use is rubocop report which will print fail details vs. a certain string if NO fails.


jobs:
  printbad:
    runs-on: ubuntu-latest
    steps:
      - run: |
          # echo "foo bar" | tee -a /dev/tty | grep --silent "boo"
          # echo "foo bar" | tee -a /dev/stdout | grep --silent "boo"
          echo -e "foo\nbar" > loggo && cat loggo &&  grep --silent "boo" loggo

  printgood:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -e "boo\nbar" > loggo && cat loggo &&  grep --silent "boo" loggo
